server:
  port: 8082  # API Gateway'in çalışacağı port

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users-service
          uri: lb://USERS-SERVICE  # users-service'e yönlendirme (Load Balancer)
          predicates:
            - Path=/users-service/**  # Tüm /users/** isteklerini yönlendir
          filters:
            - StripPrefix=1  # /users kısmını kırpar ve devamını yönlendirir

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Eureka Server'ın adresi
  instance:
    prefer-ip-address: true
