spring:
  application:
    name: gateway-server # Uygulamanın adı, Config Server'dan bu adla yapılandırma alınır
  cloud:
    config:
      uri: http://localhost:8012  # Config Server URL
      fail-fast: true             # Config Server'a bağlanamazsa uygulama başlatılamaz

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL
